wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1660540397.88415
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 17
      - 23
      - 37
      4: 3.8.10
      5: 0.13.1
      8:
      - 5
      10:
      - 9
